version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: mtc_pg
    restart: always
    environment:
      POSTGRES_USER: mtc
      POSTGRES_PASSWORD: mtc123
      POSTGRES_DB: mtcdb
    ports:
      - "5433:5432"
    volumes:
      - pg_mtc_data:/var/lib/postgresql/data

volumes:
  pg_mtc_data:
